rules:
  indentation:
    - 2
    -
      size: 4
  variable-name-format:
    - 1
    -
      convention: 'camelcase'
  clean-import-paths:
    - 0
  property-sort-order:
    - 0
  no-color-literals:
    - 0
  class-name-format:
    - 0
  no-vendor-prefixes:
    - 0
